- name: Install clamav
  apt:
    pkg:
    - clamav
    - clamav-daemon
    - clamav-freshclam
    - clamav-unofficial-sigs
    state: latest
    update_cache: true

- name: Install pyclamd
  pip:
    name:
    - pyclamd
    executable: pip3

- name: Configure settings for the clamav-unofficial-sigs.sh
  template:
    src: 00-clamav-unofficial-sigs.conf.j2
    dest: /usr/share/clamav-unofficial-sigs/conf.d/00-clamav-unofficial-sigs.conf
    owner: root
    group: root
    mode: 0644

- name: Temporary stop clamav-freshclam
  systemd:
    name: clamav-freshclam
    state: stopped
    daemon_reload: true

- name: Temporary stop clamav-daemon
  systemd:
    name: clamav-daemon
    state: stopped
    daemon_reload: true

- name: Manually run freshclam once
  shell:
    cmd: freshclam
    creates: /var/lib/clamav/daily.cld

- name: Start clamav-freshclam is enable the service to run on boot
  systemd:
    name: clamav-freshclam
    state: started
    enabled: true
    daemon_reload: true

- name: Start clamav-daemon is enable the service to run on boot
  systemd:
    name: clamav-daemon
    state: started
    enabled: true
    daemon_reload: true

- name: Run clamav-unofficial-sigs.sh
  shell:
    cmd: /usr/sbin/clamav-unofficial-sigs
  become: true
  become_user: clamav
  tags:
  - clamav-unofficial-sigs