- name: Deploy Cape V2
  hosts: localhost
  become: true
  roles: ['capev2dependencies', 'clamav', 'redsocks2', 'mongodb', 'postgresql', 'suricata', 'tor', 'yara', 'jemalloc', 'capev2', 'customcapev2tweaks', 'capenginx', 'fail2ban']