- name: Deploy Cape V2
  hosts: cape_host
  become: true
  roles: ['capev2dependencies', 'docker', 'boxjs', 'capa', 'clamav', 'redsocks2', 'mongodb', 'postgresql', 'capesuricata', 'tor', 'yara', 'jemalloc', 'capev2', 'customcapev2tweaks', 'capenginx', 'fail2ban']