---
cape_user: "cape"
cape_db_user: "cape"
cape_db_password: "changeme"

cape_ip: "127.0.0.1"
cape_vm_subnet_ip: "192.168.100.1"
cape_vm_subnet_interface: "virbr1"
cape_nr_processor: 2
cape_machinery: "kvm"
cape_inetsim_interface: "virbr1"

external_fqdn: "localhost"

inetsim_ip: "192.168.100.2"
inetsim_dns_port: 53

proxmox_ip: "127.0.0.1"
proxmox_user: "root"
proxmox_password: "changeme"
proxmox_active_vms: "win7"
proxmox_vms:
  - name: "win7"
    platform: "windows"
    ip: "192.168.100.10"
    snapshot: "clean"
    tags: "64x"

misp_enabled: "no"
misp_url: "https://localhost"
misp_apikey: "REPLACE_ME"
misp_auto_publish: "no"
misp_min_malscore: 0
misp_enrich_cape_report: "no"
misp_distribution: 0
misp_report_threat_level_id: 2
misp_report_analysis_state: 2
misp_send_ioc: "no"
misp_include_network_ioc: "yes"
misp_include_ids_ioc: "yes"
misp_include_dropedfiles_ioc: "yes"
misp_include_registry_ioc: "no"
misp_include_mutexes_ioc: "no"