
- name: Add suricata deb repo
  apt_repository:
    repo: "ppa:oisf/suricata-stable"
    filename: suricata_stable
    state: present

- name: Install suricata
  apt:
    pkg:
    - suricata
    state: latest

- name: "Create group suricata"
  group:
    name: "suricata"
    state: present

- name: Create /etc/suricata/threshold.config
  file:
    path: /etc/suricata/threshold.config
    state: touch

- name: Install python package for updating suricata rules
  pip:
    name:
    - suricata-update
    executable: pip3

- name: Setup directory for hosting rules
  file:
    path: /etc/suricata/rules
    state: directory
    recurse: true

- name: Create cronjob for updating rules
  cron:
    name: update suricata rules
    minute: "15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "/usr/bin/suricata-update --suricata /usr/bin/suricata --suricata-conf /etc/suricata/suricata.yaml -o /etc/suricata/rules/"
    cron_file: ansible_suricata_rules_autoupdate

- name: Adjust suricata configuration /etc/default/suricata
  lineinfile:
    dest: /etc/default/suricata
    line: "{{ item.value }}"
    regexp: "^{{ item.name }}"
  with_items:
    - name: "RUN="
      value: "RUN=no"
    - name: "#default-rule-path: /etc/suricata/rules"
      value: "default-rule-path: /etc/suricata/rules"

- name: Adjust suricata configuration /etc/suricata/suricata.yaml
  lineinfile:
    dest: /etc/suricata/suricata.yaml
    line: "{{ item.value }}"
    regexp: "^{{ item.name }}"
  with_items:
    - name: "#?rule-files:"
      value: "rule-files:"
    - name: "#?  - suricata.rules"
      value: "  - suricata.rules"
    - name: "mpm-algo:"
      value: "mpm-algo: auto"
    - name: "#?run-as:"
      value: "run-as:"
    - name: "#?  user:"
      value: "  user: {{ cape_user }}"
    - name: "#?  group:"
      value: "  group: {{ cape_user }}"
    - name: "    depth:"
      value: "    depth: 0"
    - name: "           request-body-limit:"
      value: "           request-body-limit: 0"
    - name: "           response-body-limit:"
      value: "           response-body-limit: 0"
    - name: "    EXTERNAL_NET: "
      value: "    EXTERNAL_NET: \"ANY\""
    - name: "#checksum-validation: "
      value: "checksum-validation: nones"

- name: Set permissions for /var/run/suricata
  file:
    path: /var/run/suricata
    state: directory
    mode: 0775
    group: suricata

- name: Enable eve-log in suricata configuration /etc/suricata/suricata.yaml
  lineinfile:
    dest: /etc/suricata/suricata.yaml
    line: "\\1 yes"
    regexp: "^(.*eve-log:\\n.*enabled:).*$"
    backrefs: true

# Skipped changing custom socket path

- name: Set ownership of /etc/suricata
  file:
    path: /etc/suricata
    state: directory
    group: "suricata"
    owner: "{{ cape_user }}"

- name: Set permissions for /var/lib/suricata/rules
  file:
    path: /var/lib/suricata/rules
    state: directory
    mode: 0655
    group: suricata
    recurse: true

- name: Set permissions for /var/lib/suricata/update
  file:
    path: /var/lib/suricata/update
    state: directory
    mode: 0655
    group: suricata
    recurse: true

- name: Run suricata rule update manually once
  shell:
    cmd: "/usr/bin/suricata-update --suricata /usr/bin/suricata --suricata-conf /etc/suricata/suricata.yaml -o /etc/suricata/rules/"
    creates: /var/lib/suricata/rules/suricata.rules

- name: Create cronjob for reloading rules
  cron:
    name: reload suricata rules
    minute: "16"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "/usr/bin/suricatasc -c reload-rules"
    cron_file: ansible_suricata_rules_reload