- name: Install Docker GPG-KEY
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install/enable https apt transport
  apt:
    name: apt-transport-https
    update_cache: true

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest

- name: Install python3
  apt:
    name: python3
    state: present
    update_cache: true

- name: Install python3-dev
  apt:
    name: python3-dev
    state: present

- name: Get pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip3
  shell: python3 /tmp/get-pip.py

- name: Make sure python package docker-compose is present
  pip:
    name: docker-compose
    state: present

- name: Get docker-compose binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0775
